# -*- coding: utf-8 -*-
"""Phishingemial_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fX3gAjAcvoTOFGY3FdrmXoOG_f0-RjtS
"""

# -*- coding: utf-8 -*-
"""PhishingEmail_Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fIjxi-dPVtvTrR7zb2DKdx0_lYShKjy
"""

# -*- coding: utf-8 -*-
"""PhishingEmail.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1al3C4Ck1s9OZijxasFpv5JPNhS_MJyjR
"""

# SECTION 1 — INSTALL PACKAGES
import subprocess, sys

print("Installing packages — please wait...")
pkgs = ["transformers","accelerate","scikit-learn","imbalanced-learn",
        "xgboost","shap","matplotlib","seaborn","wordcloud",
        "nltk","beautifulsoup4","lxml","pandas","numpy","tqdm","flask"]
for p in pkgs:
    subprocess.check_call([sys.executable,"-m","pip","install","-q",p])
print("✅ Packages ready\n")

import io, re, os, warnings, threading, time
import numpy as np
from flask import Flask, request, jsonify
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from collections import Counter
from bs4 import BeautifulSoup
from wordcloud import WordCloud
warnings.filterwarnings("ignore")

import nltk
nltk.download("stopwords", quiet=True)
nltk.download("wordnet",   quiet=True)
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import (accuracy_score, f1_score, precision_score,
                              recall_score, classification_report, confusion_matrix)
from xgboost import XGBClassifier
import shap

from transformers import (RobertaTokenizer, RobertaForSequenceClassification,
                           get_linear_schedule_with_warmup)
from torch.optim import AdamW

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"🖥️  Device: {DEVICE}")
if DEVICE.type == "cuda":
    print(f"   GPU : {torch.cuda.get_device_name(0)}")
else:
    print("    No GPU — go to Runtime > Change runtime type > T4 GPU")

# SECTION 2 — UPLOAD & LOAD DATASET

print("SECTION 2 — UPLOAD DATASET")

from google.colab import files
uploaded = files.upload()          # ← shows the file picker in Colab

# Get the uploaded file name (works regardless of what the user named the file)
uploaded_filename = list(uploaded.keys())[0]
print(f"\n✅ Received: {uploaded_filename}")

# Read into DataFrame directly from the uploaded bytes — no path needed
df_raw = pd.read_csv(io.BytesIO(uploaded[uploaded_filename]))
print(f"   Rows loaded : {len(df_raw):,}")
print(f"   Columns     : {list(df_raw.columns)}")

col_rename = {}
for col in df_raw.columns:
    cl = col.lower().strip()
    if cl in ["email text","email_text","body","content","message","email","text"]:
        col_rename[col] = "text"
    if cl in ["email type","email_type","label","class","category","type"]:
        col_rename[col] = "label"
df_raw = df_raw.rename(columns=col_rename)

if "text" not in df_raw.columns or "label" not in df_raw.columns:
    raise ValueError(
        f"\n❌  Could not find 'text' and 'label' columns.\n"
        f"   Columns in your file: {list(df_raw.columns)}\n"
        "   Make sure you uploaded  phishing_dataset.csv  (the file provided)."
    )

label_map = {"safe email":"ham","legitimate":"ham","benign":"ham","ham":"ham",
             "phishing email":"phishing","phishing":"phishing","phish":"phishing",
             "spam":"spam","junk":"spam"}
df_raw["label"] = df_raw["label"].astype(str).str.lower().str.strip().map(label_map)
df_raw = (df_raw[df_raw["label"].isin(["ham","spam","phishing"])]
          .dropna(subset=["text","label"])
          .reset_index(drop=True))

print(f"\n   Label distribution:")
print(df_raw["label"].value_counts().to_string())

missing = [c for c in ["ham","spam","phishing"] if c not in df_raw["label"].values]
if missing:
    raise ValueError(
        f"\n❌  Missing classes: {missing}\n"
        "   The dataset must contain ham, spam AND phishing emails.\n"
        "   Please upload the  phishing_dataset.csv  file that was provided.\n"
    )
print(f"\n✅ All 3 classes confirmed: ham ✓   spam ✓   phishing ✓")

# SECTION 3 — TEXT PREPROCESSING PIPELINE
print("SECTION 3 — PREPROCESSING")
STOPWORDS     = set(stopwords.words("english"))
lemmatizer    = WordNetLemmatizer()
URGENCY_WORDS = ["urgent","immediately","verify","suspended","limited","expires",
                 "confirm","restricted","blocked","login","password","account"]
LABEL_ENC     = {"ham":0,"spam":1,"phishing":2}
LABEL_NAMES   = ["ham","spam","phishing"]
COLOURS       = {"ham":"#22c55e","spam":"#f97316","phishing":"#ef4444"}

def clean_text(text: str) -> str:
    # 1 strip HTML
    text = BeautifulSoup(str(text), "lxml").get_text(separator=" ")
    # 2 remove email headers
    for p in [r"From:.*?\n",r"To:.*?\n",r"Subject:.*?\n",r"-----Original Message-----.*"]:
        text = re.sub(p," ",text,flags=re.IGNORECASE|re.DOTALL)
    # 3 replace email addresses
    text = re.sub(r"[\w\.\-]+@[\w\.\-]+\.\w+"," EMAILTOKEN ",text)
    # 4 replace money amounts
    text = re.sub(r"[£$€]\s?\d[\d,\.]*"," MONEYTOKEN ",text)
    # 5 replace URLs — keep URLTOKEN as a phishing signal
    text = re.sub(r"http[s]?://\S+"," URLTOKEN ",text)
    # 6 lowercase
    text = text.lower()
    # 7 remove punctuation / special chars
    text = re.sub(r"[^a-z0-9\s]"," ",text)
    text = re.sub(r"\b\d{5,}\b"," ",text)
    text = re.sub(r"\s+"," ",text).strip()
    # 8 lemmatise — keep placeholder tokens even if they match stopwords
    tokens = [lemmatizer.lemmatize(t) for t in text.split()
              if t not in STOPWORDS or "token" in t]
    return " ".join(tokens)

print("Cleaning emails...")
df_raw["cleaned_text"] = df_raw["text"].apply(clean_text)

raw = df_raw["text"].fillna("").astype(str)
df_raw["url_count"]         = raw.apply(lambda t: len(re.findall(r"http[s]?://\S+",t)))
df_raw["has_url"]           = (df_raw["url_count"] > 0).astype(int)
df_raw["exclamation_count"] = raw.apply(lambda t: t.count("!"))
df_raw["caps_ratio"]        = raw.apply(lambda t: sum(1 for c in t if c.isupper()) /
                                         max(len([c for c in t if c.isalpha()]),1))
df_raw["word_count"]    = df_raw["cleaned_text"].apply(lambda t: len(str(t).split()))
df_raw["urgency_score"] = raw.apply(lambda t: sum(1 for w in URGENCY_WORDS if w in t.lower()))
df_raw = df_raw[df_raw["cleaned_text"].str.len()>10].reset_index(drop=True)
df_raw["label_id"] = df_raw["label"].map(LABEL_ENC)

print(f"✅ Preprocessing done — {len(df_raw):,} emails ready")
print(df_raw.groupby("label")[["url_count","urgency_score","caps_ratio","exclamation_count"]]
      .mean().round(3).to_string())

# SECTION 4 — EXPLORATORY DATA ANALYSIS
print("SECTION 4 — EDA VISUALISATIONS")
fig = plt.figure(figsize=(18,14))
gs  = gridspec.GridSpec(3,3,figure=fig,hspace=0.45,wspace=0.35)

# 1. Class Distribution
ax1 = fig.add_subplot(gs[0,0])
counts = df_raw["label"].value_counts()
bars = ax1.bar(counts.index,counts.values,
               color=[COLOURS[l] for l in counts.index],edgecolor="white")
ax1.set_title("Class Distribution",fontweight="bold",fontsize=12)
ax1.set_ylabel("Count")
for bar,val in zip(bars,counts.values):
    ax1.text(bar.get_x()+bar.get_width()/2,bar.get_height()+0.2,
             str(val),ha="center",fontsize=9,fontweight="bold")

# 2. Word Count
ax2 = fig.add_subplot(gs[0,1])
for lbl in LABEL_NAMES:
    ax2.hist(df_raw[df_raw["label"]==lbl]["word_count"].clip(0,150),
             bins=20,alpha=0.65,label=lbl,color=COLOURS[lbl])
ax2.set_title("Word Count per Class",fontweight="bold",fontsize=12)
ax2.set_xlabel("Word Count"); ax2.legend()

# 3. Average URL Count
ax3 = fig.add_subplot(gs[0,2])
url_m = df_raw.groupby("label")["url_count"].mean()
ax3.bar(url_m.index,url_m.values,color=[COLOURS[l] for l in url_m.index])
ax3.set_title("Average URL Count per Class",fontweight="bold",fontsize=12)

# 4. Exclamation Boxplot
ax4 = fig.add_subplot(gs[1,0])
for i,lbl in enumerate(LABEL_NAMES):
    data = df_raw[df_raw["label"]==lbl]["exclamation_count"].clip(0,15)
    ax4.boxplot(data,positions=[i],widths=0.5,patch_artist=True,
                boxprops=dict(facecolor=COLOURS[lbl],alpha=0.7))
ax4.set_xticks([0,1,2]); ax4.set_xticklabels(LABEL_NAMES)
ax4.set_title("Exclamation Count (clipped at 15)",fontweight="bold",fontsize=12)

# 5. Caps Ratio
ax5 = fig.add_subplot(gs[1,1])
for lbl in LABEL_NAMES:
    ax5.hist(df_raw[df_raw["label"]==lbl]["caps_ratio"].clip(0,0.5),
             bins=20,alpha=0.65,label=lbl,color=COLOURS[lbl])
ax5.set_title("Capitalisation Ratio per Class",fontweight="bold",fontsize=12)
ax5.legend()

# 6. Urgency Score
ax6 = fig.add_subplot(gs[1,2])
urg = df_raw.groupby("label")["urgency_score"].mean()
ax6.bar(urg.index,urg.values,color=[COLOURS[l] for l in urg.index])
ax6.set_title("Average Urgency Score per Class",fontweight="bold",fontsize=12)

# 7-9. Word Clouds
for col_idx,lbl in enumerate(LABEL_NAMES):
    ax = fig.add_subplot(gs[2,col_idx])
    corpus = " ".join(df_raw[df_raw["label"]==lbl]["cleaned_text"].dropna())
    if len(corpus) > 50:
        cmap = "Greens" if lbl=="ham" else ("Oranges" if lbl=="spam" else "Reds")
        wc = WordCloud(width=400,height=240,background_color="white",
                       colormap=cmap,max_words=60).generate(corpus)
        ax.imshow(wc,interpolation="bilinear")
    ax.axis("off")
    ax.set_title(f"Word Cloud — {lbl.upper()}",fontweight="bold",
                 fontsize=12,color=COLOURS[lbl])

fig.suptitle("Exploratory Data Analysis — Phishing Email Detection Dataset",
             fontsize=14,fontweight="bold",y=1.01)
plt.savefig("eda_visualisations.png",dpi=150,bbox_inches="tight")
plt.show()
print("✅ Saved: eda_visualisations.png")

# SECTION 5 — TRAIN / VAL / TEST SPLIT + TF-IDF
print("SECTION 5 — DATA SPLITTING + TF-IDF")
X = df_raw["cleaned_text"].fillna("").astype(str)
y = df_raw["label_id"].values

X_train,X_temp,y_train,y_temp = train_test_split(X,y,test_size=0.30,random_state=42,stratify=y)
X_val,X_test,y_val,y_test     = train_test_split(X_temp,y_temp,test_size=0.50,random_state=42,stratify=y_temp)

print(f"Train : {len(X_train):,}  |  Val : {len(X_val):,}  |  Test : {len(X_test):,}")

# min_df=1 because dataset is small (89 emails)
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),sublinear_tf=True,
                        strip_accents="unicode",min_df=1,max_df=0.95)
X_train_tfidf = tfidf.fit_transform(X_train)
X_val_tfidf   = tfidf.transform(X_val)
X_test_tfidf  = tfidf.transform(X_test)
print(f"TF-IDF vocabulary : {len(tfidf.vocabulary_):,} features")

# SECTION 6 — BASELINE ML MODELS
print("SECTION 6 — BASELINE ML MODELS")
# NOTE: multi_class param removed in scikit-learn 1.6+ — do NOT add it back
baseline_models = {
    "Logistic Regression" : LogisticRegression(C=1.0,max_iter=1000,
                                                class_weight="balanced",random_state=42),
    "Naive Bayes"         : MultinomialNB(alpha=0.1),
    "SVM (LinearSVC)"     : LinearSVC(C=1.0,class_weight="balanced",
                                       max_iter=2000,random_state=42),
    "Random Forest"       : RandomForestClassifier(n_estimators=100,
                                                    class_weight="balanced",
                                                    random_state=42,n_jobs=-1),
    "XGBoost"             : XGBClassifier(n_estimators=100,learning_rate=0.1,
                                           max_depth=4,eval_metric="mlogloss",
                                           random_state=42,n_jobs=-1,verbosity=0),
}

baseline_results = []
for name,clf in baseline_models.items():
    print(f"\n  Training: {name}...", end=" ", flush=True)
    clf.fit(X_train_tfidf,y_train)
    y_pred   = clf.predict(X_test_tfidf)
    acc      = accuracy_score(y_test,y_pred)
    macro_f1 = f1_score(y_test,y_pred,average="macro",zero_division=0)
    per_rec  = recall_score(y_test,y_pred,average=None,zero_division=0)
    fnr      = 1-per_rec[2] if len(per_rec)>2 else 0.0
    baseline_results.append({"Model":name,"Accuracy":round(acc,4),
                              "Macro F1":round(macro_f1,4),"Phishing FNR":round(fnr,4)})
    print(f"Acc={acc:.4f}  F1={macro_f1:.4f}  Phish-FNR={fnr:.4f}")

results_df = pd.DataFrame(baseline_results)
print(results_df.to_string(index=False))
results_df.to_csv("baseline_results.csv",index=False)
print("\n✅ Saved: baseline_results.csv")

# SECTION 7 — IMPROVEMENT 1: RoBERTa FINE-TUNING
# WHY RoBERTa: removes NSP task, 10x more training data, dynamic masking
# → +1.5-3% F1 over BERT (Melendez et al. 2024, Jamal et al. 2024)
print("SECTION 7 — IMPROVEMENT 1: RoBERTa FINE-TUNING")
MODEL_NAME   = "roberta-base"
MAX_LEN      = 256    # balances accuracy vs GPU memory
BATCH_SIZE   = 16     # reduce to 8 if CUDA out-of-memory error appears
EPOCHS       = 4
LR           = 2e-5
WARMUP_RATIO = 0.1
NUM_LABELS   = 3

class EmailDataset(Dataset):
    def __init__(self,texts,labels,tokenizer,max_len):
        self.texts=list(texts); self.labels=list(labels)
        self.tokenizer=tokenizer; self.max_len=max_len
    def __len__(self): return len(self.texts)
    def __getitem__(self,idx):
        enc = self.tokenizer(self.texts[idx],max_length=self.max_len,
                             padding="max_length",truncation=True,return_tensors="pt")
        return {"input_ids"     : enc["input_ids"].squeeze(0),
                "attention_mask": enc["attention_mask"].squeeze(0),
                "label"         : torch.tensor(self.labels[idx],dtype=torch.long)}

print(f"Loading {MODEL_NAME}...")
tokenizer = RobertaTokenizer.from_pretrained(MODEL_NAME)
model     = RobertaForSequenceClassification.from_pretrained(
    MODEL_NAME,num_labels=NUM_LABELS,
    hidden_dropout_prob=0.1,attention_probs_dropout_prob=0.1).to(DEVICE)
print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")

train_ds = EmailDataset(X_train.tolist(),y_train,tokenizer,MAX_LEN)
val_ds   = EmailDataset(X_val.tolist(),  y_val,  tokenizer,MAX_LEN)
test_ds  = EmailDataset(X_test.tolist(), y_test, tokenizer,MAX_LEN)
train_dl = DataLoader(train_ds,batch_size=BATCH_SIZE,shuffle=True, num_workers=2,pin_memory=True)
val_dl   = DataLoader(val_ds,  batch_size=BATCH_SIZE,shuffle=False,num_workers=2,pin_memory=True)
test_dl  = DataLoader(test_ds, batch_size=BATCH_SIZE,shuffle=False,num_workers=2,pin_memory=True)

optimizer   = AdamW(model.parameters(),lr=LR,eps=1e-8,weight_decay=0.01)
total_steps = len(train_dl)*EPOCHS
scheduler   = get_linear_schedule_with_warmup(optimizer,
                  num_warmup_steps=int(total_steps*WARMUP_RATIO),
                  num_training_steps=total_steps)

# Class-weighted loss: upweights phishing (label 2) × 2.5 to reduce false-negatives
class_weights = torch.tensor([1.0,1.5,2.5]).to(DEVICE)
loss_fn = nn.CrossEntropyLoss(weight=class_weights)

training_history = []; best_val_f1 = 0.0

for epoch in range(EPOCHS):
    print(f"  Epoch {epoch+1}/{EPOCHS}")
    model.train(); total_loss = 0.0
    for batch in train_dl:
        optimizer.zero_grad()
        out  = model(input_ids=batch["input_ids"].to(DEVICE),
                     attention_mask=batch["attention_mask"].to(DEVICE))
        loss = loss_fn(out.logits,batch["label"].to(DEVICE))
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(),1.0)
        optimizer.step(); scheduler.step()
        total_loss += loss.item()
    avg_loss = total_loss/len(train_dl)

    model.eval(); val_preds,val_true = [],[]
    with torch.no_grad():
        for batch in val_dl:
            out = model(input_ids=batch["input_ids"].to(DEVICE),
                        attention_mask=batch["attention_mask"].to(DEVICE))
            val_preds.extend(torch.argmax(out.logits,dim=1).cpu().numpy())
            val_true.extend(batch["label"].numpy())
    val_f1  = f1_score(val_true,val_preds,average="macro",zero_division=0)
    val_acc = accuracy_score(val_true,val_preds)
    print(f"  Train Loss={avg_loss:.4f}  Val Acc={val_acc:.4f}  Val F1={val_f1:.4f}")
    training_history.append({"epoch":epoch+1,"train_loss":avg_loss,
                              "val_acc":val_acc,"val_f1":val_f1})
    if val_f1 > best_val_f1:
        best_val_f1 = val_f1
        torch.save(model.state_dict(),"roberta_best.pt")
        print(f"  ✅ Best model saved (F1={val_f1:.4f})")

# Test evaluation
print("\n  Loading best checkpoint for test evaluation...")
model.load_state_dict(torch.load("roberta_best.pt"))
model.eval(); test_preds,test_true = [],[]
with torch.no_grad():
    for batch in test_dl:
        out = model(input_ids=batch["input_ids"].to(DEVICE),
                    attention_mask=batch["attention_mask"].to(DEVICE))
        test_preds.extend(torch.argmax(out.logits,dim=1).cpu().numpy())
        test_true.extend(batch["label"].numpy())

roberta_acc = accuracy_score(test_true,test_preds)
roberta_f1  = f1_score(test_true,test_preds,average="macro",zero_division=0)
per_rec      = recall_score(test_true,test_preds,average=None,zero_division=0)
roberta_fnr  = 1-per_rec[2] if len(per_rec)>2 else 0.0
print(f"\n  ✅ RoBERTa — Acc={roberta_acc:.4f}  F1={roberta_f1:.4f}  Phish-FNR={roberta_fnr:.4f}")
print(classification_report(test_true,test_preds,target_names=LABEL_NAMES,zero_division=0))

# Training curve plot
hist_df = pd.DataFrame(training_history)
fig,axes = plt.subplots(1,2,figsize=(12,4))
axes[0].plot(hist_df["epoch"],hist_df["train_loss"],"b-o",linewidth=2)
axes[0].set_title("RoBERTa Training Loss",fontweight="bold")
axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Loss")
axes[1].plot(hist_df["epoch"],hist_df["val_f1"],"g-o",linewidth=2)
axes[1].set_title("RoBERTa Validation Macro F1",fontweight="bold")
axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("Macro F1")
plt.tight_layout()
plt.savefig("roberta_training_curve.png",dpi=150,bbox_inches="tight")
plt.show()
print("✅ Saved: roberta_training_curve.png")

# SECTION 8 — IMPROVEMENT 2: ENSEMBLE STACKING (SVM + RoBERTa)
# WHY: Fuses lexical strength of TF-IDF+SVM with semantic strength of RoBERTa
# Aljabri & Alharbi (2025): ensembles outperform single models by avg 4.7%
print("SECTION 8 — IMPROVEMENT 2: ENSEMBLE STACKING")
def get_roberta_probs(loader,mdl,dev):
    mdl.eval(); all_probs=[]
    with torch.no_grad():
        for batch in loader:
            out   = mdl(input_ids=batch["input_ids"].to(dev),
                        attention_mask=batch["attention_mask"].to(dev))
            probs = torch.softmax(out.logits,dim=1).cpu().numpy()
            all_probs.append(probs)
    return np.vstack(all_probs)

# Cap cv folds to min class count — prevents StratifiedKFold error on small datasets
min_class = min(Counter(y_train).values())
cv_folds  = min(3,min_class)
print(f"  Calibrating SVM (cv={cv_folds})...")
svm_cal = CalibratedClassifierCV(LinearSVC(C=1.0,class_weight="balanced",random_state=42),
                                  cv=cv_folds,method="isotonic")
svm_cal.fit(X_train_tfidf,y_train)

print("  Extracting probability vectors...")
train_svm_probs     = svm_cal.predict_proba(X_train_tfidf)
test_svm_probs      = svm_cal.predict_proba(X_test_tfidf)
train_roberta_probs = get_roberta_probs(train_dl,model,DEVICE)
test_roberta_probs  = get_roberta_probs(test_dl,model,DEVICE)

# Meta-features: [SVM_p(ham), SVM_p(spam), SVM_p(phish),
#                 Rob_p(ham), Rob_p(spam), Rob_p(phish)]
X_meta_train = np.hstack([train_svm_probs,train_roberta_probs])
X_meta_test  = np.hstack([test_svm_probs, test_roberta_probs])
print(f"  Meta-feature matrix: {X_meta_train.shape}")

print("  Training Logistic Regression meta-learner...")
meta_clf       = LogisticRegression(C=10.0,max_iter=1000,random_state=42)
meta_clf.fit(X_meta_train,y_train)
ensemble_preds = meta_clf.predict(X_meta_test)

ensemble_acc = accuracy_score(y_test,ensemble_preds)
ensemble_f1  = f1_score(y_test,ensemble_preds,average="macro",zero_division=0)
per_rec       = recall_score(y_test,ensemble_preds,average=None,zero_division=0)
ensemble_fnr  = 1-per_rec[2] if len(per_rec)>2 else 0.0
print(f"\n  ✅ Ensemble — Acc={ensemble_acc:.4f}  F1={ensemble_f1:.4f}  Phish-FNR={ensemble_fnr:.4f}")
print(classification_report(y_test,ensemble_preds,target_names=LABEL_NAMES,zero_division=0))

# SECTION 9 — IMPROVEMENT 3: SHAP EXPLAINABILITY
# WHY: Identifies which words drive each prediction — fills interpretability gap
# Lundberg & Lee (2017); Mahboob et al. (2025)
#
# ⚠️  IMPORTANT: LinearExplainer returns shape (n_samples, n_features, n_classes)
#     Access class k with:  sv[:, :, k]    NOT  sv[k]
print("SECTION 9 — IMPROVEMENT 3: SHAP EXPLAINABILITY")
lr_shap = LogisticRegression(C=1.0,max_iter=1000,class_weight="balanced",random_state=42)
lr_shap.fit(X_train_tfidf,y_train)

print("  Computing SHAP values (may take 1-2 minutes)...")
background  = shap.sample(X_train_tfidf,min(50,len(X_train)),random_state=42)
explainer   = shap.LinearExplainer(lr_shap,background,feature_perturbation="interventional")
n_explain   = min(30,len(X_test))
sv          = explainer.shap_values(X_test_tfidf[:n_explain])
# sv shape → (n_explain, n_features, n_classes)
feat_names  = tfidf.get_feature_names_out()
print(f"  SHAP array shape: {sv.shape}  ← (samples, features, classes)")

# Plot 1: Dot summary for phishing class — sv[:,:,2] = phishing slice
plt.figure(figsize=(12,8))
shap.summary_plot(sv[:,:,2], X_test_tfidf[:n_explain],
                  feature_names=feat_names, max_display=15,
                  show=False, plot_type="dot")
plt.title("SHAP — Phishing Class (Top 15 Words)\n"
          "Red = pushes toward phishing  |  Blue = pushes away",
          fontsize=11,fontweight="bold")
plt.tight_layout()
plt.savefig("shap_phishing.png",dpi=150,bbox_inches="tight")
plt.show()

# Plot 2: Bar chart — top features per class
fig,axes = plt.subplots(1,3,figsize=(18,6))
for idx,(ax,cls) in enumerate(zip(axes,LABEL_NAMES)):
    sv_cls   = sv[:,:,idx]                     # (n_explain, n_features)
    mean_abs = np.abs(sv_cls).mean(axis=0)     # (n_features,)
    top_n    = min(15,len(mean_abs))
    top_idx  = np.argsort(mean_abs)[-top_n:]
    ax.barh([feat_names[i] for i in top_idx],mean_abs[top_idx],
            color=["#22c55e","#f97316","#ef4444"][idx],alpha=0.85)
    ax.set_title(f"SHAP Top Features — {cls.upper()}",fontweight="bold",fontsize=11)
    ax.set_xlabel("Mean |SHAP Value|")
plt.suptitle("SHAP Feature Importance by Email Class",fontsize=13,fontweight="bold")
plt.tight_layout()
plt.savefig("shap_all_classes.png",dpi=150,bbox_inches="tight")
plt.show()
print("✅ Saved: shap_phishing.png  |  shap_all_classes.png")

# SECTION 10 — IMPROVEMENT 4: ADVERSARIAL ROBUSTNESS TEST

print("SECTION 10 — IMPROVEMENT 4: ADVERSARIAL ROBUSTNESS")
print("Ground truth for all 5 test emails = phishing")
print("Detection rate = % correctly identified as phishing despite obfuscation\n")

original_phishing = [
    "Your PayPal account has been limited. Verify your identity immediately at http://paypal-secure-verify.com/login or your account will be permanently suspended.",
    "HMRC: You are owed a tax refund of 342.50 pounds. Click here to claim: http://hmrc-refund.gov.phish.tk within 24 hours.",
    "Apple ID suspended due to unusual activity. Restore access now: http://apple-verify-account.info/restore or lose your data permanently.",
    "Netflix payment failed. Update your billing information at http://netflix-billing-secure.phish.net/pay within 3 days to avoid suspension.",
    "Your Barclays account has been blocked for security reasons. Login to verify: http://barclays-secure-login.phish.com",
]

attacks = {
    "Original (no attack)": original_phishing,
    "Attack 1 — Char swap": [
        "Y0ur P4yP4l 4cc0unt h4s b33n l1m1t3d. V3r1fy 4t http://p4yp4l-s3cur3.c0m 1mm3d14t3ly.",
        "HMRC: Y0u 0w3d 342.50 r3fund. Cl1ck: http://hmrc-r3fund.phish.tk",
        "4ppl3 ID susp3nd3d. R3st0r3: http://4ppl3-v3r1fy.1nf0/r3st0r3",
        "N3tfl1x p4ym3nt f41l3d. Upd4t3: http://n3tfl1x-b1ll1ng.ph1sh.n3t/p4y",
        "B4rcl4ys 4cc0unt bl0ck3d. L0g1n: http://b4rcl4ys-l0g1n.ph1sh.c0m",
    ],
    "Attack 2 — Synonyms": [
        "Your PayPal profile restricted. Confirm details at http://paypal-secure-check.com/signin to avoid permanent closure.",
        "HMRC: You entitled to 342.50 pound cashback. Receive at http://hmrc-cashback.info within 24 hours.",
        "Apple account deactivated. Reinstate at http://apple-check-profile.info/reactivate or lose all data.",
        "Netflix transaction declined. Revise payment at http://netflix-payment-portal.info/update within 3 days.",
        "Barclays profile frozen. Authenticate at http://barclays-profile-check.info/auth",
    ],
    "Attack 3 — Whitespace": [
        "Your Pay Pal account has been lim ited. Ver ify at htt p://paypal-sec ure.com",
        "HMRC: You are ow ed 342.50 re fund. Cli ck: htt p://hmrc-re fund.tk",
        "App le ID sus pended. Rest ore: htt p://apple-ver ify.info",
        "Net flix pay ment fail ed. Up date: htt p://netf lix-bill ing.net",
        "Bar clays acc ount bloc ked. Log in: htt p://barcl ays-log in.com",
    ],
}

print(f"  {'Attack Type':<30} {'SVM+TF-IDF':>14} {'RoBERTa':>12}  {'Winner'}")

adv_results = {}
for attack_name,emails in attacks.items():
    # SVM detection
    cleaned   = [clean_text(e) for e in emails]
    svm_preds = svm_cal.predict(tfidf.transform(cleaned))
    svm_rate  = sum(1 for p in svm_preds if p==2)/len(svm_preds)

    # RoBERTa detection
    model.eval(); rob_preds=[]
    for em in emails:
        enc = tokenizer(clean_text(em),max_length=MAX_LEN,
                        padding="max_length",truncation=True,return_tensors="pt")
        with torch.no_grad():
            out = model(input_ids=enc["input_ids"].to(DEVICE),
                        attention_mask=enc["attention_mask"].to(DEVICE))
            rob_preds.append(torch.argmax(out.logits,dim=1).item())
    rob_rate = sum(1 for p in rob_preds if p==2)/len(rob_preds)

    adv_results[attack_name] = {"SVM":svm_rate,"RoBERTa":rob_rate}
    winner = "RoBERTa ✓" if rob_rate>svm_rate else "SVM ✓" if svm_rate>rob_rate else "Tied"
    print(f"  {attack_name:<30} {svm_rate*100:>12.1f}%  {rob_rate*100:>10.1f}%   {winner}")

print("\n  100% = all emails correctly identified despite the attack")
print("  Lower % = model tricked by that obfuscation technique")

# SECTION 11 — FINAL RESULTS + DISSERTATION FIGURES
print("SECTION 11 — FINAL RESULTS & DISSERTATION FIGURES")
final_rows = list(baseline_results) + [
    {"Model":"RoBERTa (Fine-tuned)",
     "Accuracy":round(roberta_acc,4),
     "Macro F1":round(roberta_f1,4),
     "Phishing FNR":round(roberta_fnr,4)},
    {"Model":"Ensemble (SVM+RoBERTa)",
     "Accuracy":round(ensemble_acc,4),
     "Macro F1":round(ensemble_f1,4),
     "Phishing FNR":round(ensemble_fnr,4)},
]
final_df = pd.DataFrame(final_rows)
final_df.to_csv("final_all_results.csv",index=False)
print("\nFull comparison:")
print(final_df[["Model","Accuracy","Macro F1","Phishing FNR"]].to_string(index=False))

# Bar chart
fig,axes = plt.subplots(1,3,figsize=(18,7))
for ax,(metric,lower) in zip(axes,[("Accuracy",False),("Macro F1",False),("Phishing FNR",True)]):
    vals   = final_df[metric].tolist()
    models = final_df["Model"].tolist()
    best   = min(vals) if lower else max(vals)
    cols   = ["#22c55e" for _ in vals]
    ax.barh(models,vals,color=cols,edgecolor="white")
    for i,v in enumerate(vals):
        ax.text(v+0.005,i,f"{v:.4f}",va="center",fontsize=8)
    ax.set_xlim(0,max(vals)*1.18)
    ax.set_title(f"{metric}\n({'lower=better' if lower else 'higher=better'})",fontweight="bold",fontsize=11)
plt.suptitle("Model Performance Comparison — All Baselines",fontsize=13,fontweight="bold",y=1.01)
plt.tight_layout()
plt.savefig("final_model_comparison.png",dpi=150,bbox_inches="tight")
plt.show()

# Confusion matrices
svm_preds_all = svm_cal.predict(X_test_tfidf)
fig,axes = plt.subplots(1,2,figsize=(14,6))
for ax,(preds,title) in zip(axes,[(svm_preds_all,"SVM + TF-IDF (Best Baseline)"),
                                   (test_preds,   "RoBERTa Fine-tuned (Improvement 1)")]):
    cm = confusion_matrix(y_test,preds)
    sns.heatmap(cm,annot=True,fmt="d",cmap="Blues",ax=ax,
                xticklabels=LABEL_NAMES,yticklabels=LABEL_NAMES,linewidths=0.5)
    ax.set_title(f"Confusion Matrix\n{title}",fontweight="bold",fontsize=11)
    ax.set_ylabel("Actual"); ax.set_xlabel("Predicted")
plt.tight_layout()
plt.savefig("confusion_matrices.png",dpi=150,bbox_inches="tight")
plt.show()

# Output file list
# SECTION 12 — 🔍 LIVE EMAIL CHECKER
# Uses an ensemble of Naive Bayes + Logistic Regression + Calibrated SVM.
# Tests 12 emails automatically (4 ham, 4 spam, 4 phishing).
print("SECTION 12 — 🔍 LIVE EMAIL CHECKER")
# Train the three models used by the email checker
nb_model = MultinomialNB(alpha=0.1)
nb_model.fit(X_train_tfidf, y_train)

lr_model = LogisticRegression(C=1.0, max_iter=1000, class_weight="balanced", random_state=42)
lr_model.fit(X_train_tfidf, y_train)
# svm_cal is already fitted in Section 8

def predict_email(text: str) -> dict:
    """
    Predict a single email using ensemble voting of NB + LR + SVM.
    Returns label, confidence %, per-class breakdown, and signal analysis.
    """
    cleaned  = clean_text(text)
    features = tfidf.transform([cleaned])
    nb_p  = nb_model.predict_proba(features)[0]
    lr_p  = lr_model.predict_proba(features)[0]
    svm_p = svm_cal.predict_proba(features)[0]
    avg   = (nb_p + lr_p + svm_p) / 3.0
    idx   = int(np.argmax(avg))

    url_cnt   = len(re.findall(r"http[s]?://\S+", str(text)))
    exclam    = text.count("!")
    urg_words = [w for w in URGENCY_WORDS if w in text.lower()]
    caps_r    = sum(1 for c in text if c.isupper()) / max(len([c for c in text if c.isalpha()]),1)

    return {
        "label"        : LABEL_NAMES[idx],
        "confidence"   : float(avg[idx]) * 100,
        "ham_pct"      : float(avg[0]) * 100,
        "spam_pct"     : float(avg[1]) * 100,
        "phishing_pct" : float(avg[2]) * 100,
        "url_count"    : url_cnt,
        "exclamations" : exclam,
        "urgency_words": urg_words,
        "caps_ratio"   : round(caps_r * 100, 1),
    }

def print_email_result(email_text: str, true_label: str = None):
    """Pretty-print a single email prediction with full breakdown."""
    r     = predict_email(email_text)
    label = r["label"]
    icons = {"ham": "✅", "spam": "⚠️ ", "phishing": "🚨"}
    sep   = "─" * 62

    print(f"\n  {sep}")
    preview = email_text[:70] + ("..." if len(email_text) > 70 else "")
    print(f"  📧  {preview}")
    print(f"  {icons[label]}  PREDICTION : {label.upper()}   ({r['confidence']:.1f}% confidence)")
    if true_label:
        is_correct = label == true_label
        mark = "✅ CORRECT" if is_correct else f"❌ WRONG (true={true_label.upper()})"
        print(f"       True label  : {true_label.upper()}  →  {mark}")
    print(f"\n       Probabilities:")
    for cls, pct in [("ham", r["ham_pct"]), ("spam", r["spam_pct"]), ("phishing", r["phishing_pct"])]:
        bar = "█" * int(pct / 5)
        print(f"         {cls:<10} {bar:<20} {pct:>5.1f}%")
    print(f"\n       Signal analysis:")
    print(f"         URLs found       : {r['url_count']}")
    print(f"         Exclamation marks: {r['exclamations']}")
    print(f"         Caps ratio       : {r['caps_ratio']}%")
    words = r["urgency_words"]
    print(f"         Urgency words    : {', '.join(words[:5]) if words else 'none detected'}")

# 12 test emails — 4 of each class
test_emails = [
    # HAM
    ("Hi Sarah, just confirming our meeting tomorrow at 10am in the boardroom. Please bring the Q3 reports.", "ham"),
    ("Team update: deployment pipeline passed all integration tests. On track for Friday release.", "ham"),
    ("Could you review the contract amendments before Thursday? Section 3.2 needs clarification on payment terms.", "ham"),
    ("The office will be closed on Monday for the bank holiday. Normal working hours resume Tuesday at 9am.", "ham"),
    # SPAM
    ("CONGRATULATIONS!!! You have been selected to receive a FREE iPhone 15 Pro! Click here NOW: http://win-free-iphone.biz/claim", "spam"),
    ("Lose 30 pounds in 30 days GUARANTEED! NO diet! NO exercise needed! Order NOW: http://miracle-slim.ru/buy", "spam"),
    ("URGENT INVESTMENT ALERT! Stock XYZ about to EXPLODE in value! BUY NOW before the big announcement tomorrow!!!", "spam"),
    ("Make 500 dollars per day with our SECRET trading algorithm! Guaranteed returns every day! Join 50000 traders now!", "spam"),
    # PHISHING
    ("Your PayPal account has been limited due to unusual activity. Verify immediately at http://paypa1-secure-verify.com/login to avoid permanent suspension.", "phishing"),
    ("HMRC: You are owed a tax refund of 342.50 pounds. Submit claim at http://hmrc-tax-refund.gov.phish.tk and provide your bank details.", "phishing"),
    ("Dear Netflix Member, we were unable to process your payment. Update billing at http://netflix-billing-update.fakesite.info/payment or account suspended.", "phishing"),
    ("Your Apple ID has been suspended due to unusual activity. Restore access within 48 hours: http://apple-id-verify.suspicious.ml/restore", "phishing"),
]

print(f"\n  Checking {len(test_emails)} emails — 4 ham  |  4 spam  |  4 phishing\n")

correct = 0
for email_text, true_label in test_emails:
    print_email_result(email_text, true_label)
    if predict_email(email_text)["label"] == true_label:
        correct += 1

pct = correct / len(test_emails) * 100
bar = "█" * int(pct / 5)
print(f"\n  {'='*62}")
print(f"  📊  EMAIL CHECKER ACCURACY : {correct}/{len(test_emails)} correct")
print(f"       {bar} {pct:.0f}%")
print(f"  {'='*62}")


website_app = Flask(__name__)

WEBSITE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Email Threat Checker</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;
     background:#f8fafc;min-height:100vh;color:#1e293b;padding:24px}
.wrap{max-width:780px;margin:0 auto}
h1{font-size:1.7rem;font-weight:700;color:#0f172a;margin-bottom:4px}
.sub{color:#64748b;font-size:.92rem;margin-bottom:24px}
.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;
      padding:24px;margin-bottom:20px;box-shadow:0 1px 3px rgba(0,0,0,.06)}
.card h2{font-size:.85rem;font-weight:600;color:#64748b;text-transform:uppercase;
         letter-spacing:.07em;margin-bottom:14px}
/* Checkbox row */
.check-row{display:flex;gap:10px;margin-bottom:16px;flex-wrap:wrap}
.check-label{display:flex;align-items:center;gap:7px;cursor:pointer;
             padding:8px 14px;border-radius:8px;border:1.5px solid #e2e8f0;
             font-size:.92rem;font-weight:500;transition:all .15s;background:#fff}
.check-label:hover{border-color:#94a3b8;background:#f8fafc}
.check-label input[type=checkbox]{width:16px;height:16px;cursor:pointer;
   accent-color:#2563eb}
.check-label.active-ham    {border-color:#16a34a;background:#f0fdf4;color:#15803d}
.check-label.active-spam   {border-color:#d97706;background:#fffbeb;color:#b45309}
.check-label.active-phishing{border-color:#dc2626;background:#fef2f2;color:#b91c1c}
.check-note{font-size:.8rem;color:#94a3b8;margin-bottom:12px}
textarea{width:100%;border:1.5px solid #e2e8f0;border-radius:9px;
         padding:12px 14px;font-size:.95rem;font-family:inherit;
         min-height:150px;resize:vertical;outline:none;
         transition:border-color .2s;line-height:1.6;color:#1e293b}
textarea:focus{border-color:#2563eb}
textarea::placeholder{color:#94a3b8}
.btn-row{display:flex;gap:10px;margin-top:12px;flex-wrap:wrap}
button{padding:10px 22px;border-radius:8px;font-size:.95rem;font-weight:600;
       cursor:pointer;border:none;transition:all .15s}
.btn-a{background:#2563eb;color:#fff;flex:1}
.btn-a:hover{background:#1d4ed8;transform:translateY(-1px)}
.btn-a:disabled{background:#94a3b8;cursor:not-allowed;transform:none}
.btn-c{background:#f1f5f9;color:#64748b;border:1px solid #e2e8f0}
.btn-c:hover{background:#e2e8f0}
/* Examples */
.ex-row{display:flex;gap:8px;margin-bottom:14px;flex-wrap:wrap}
.ex-btn{padding:5px 13px;border-radius:6px;font-size:.8rem;cursor:pointer;
        border:1px solid #e2e8f0;background:#f8fafc;color:#475569;transition:all .15s}
.ex-btn:hover{background:#e2e8f0;color:#1e293b}
/* Spinner */
.spinner{display:none;text-align:center;padding:16px;color:#64748b;font-size:.9rem}
.spin{display:inline-block;width:18px;height:18px;border:2px solid #e2e8f0;
      border-top-color:#2563eb;border-radius:50%;
      animation:spin .7s linear infinite;vertical-align:middle;margin-right:8px}
@keyframes spin{to{transform:rotate(360deg)}}
/* Result */
.result{display:none;border-radius:12px;padding:22px;border:2px solid;
        animation:fi .25s ease}
@keyframes fi{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:translateY(0)}}
.result.ham     {background:#f0fdf4;border-color:#16a34a}
.result.spam    {background:#fffbeb;border-color:#d97706}
.result.phishing{background:#fef2f2;border-color:#dc2626}
.verdict{font-size:1.5rem;font-weight:800;margin-bottom:4px}
.verdict.ham     {color:#15803d}
.verdict.spam    {color:#b45309}
.verdict.phishing{color:#b91c1c}
.conf{font-size:.9rem;color:#64748b;margin-bottom:18px}
/* Probability bars */
.bars h3{font-size:.78rem;font-weight:600;color:#94a3b8;text-transform:uppercase;
         letter-spacing:.07em;margin-bottom:10px}
.bar-row{margin-bottom:8px}
.bar-hd{display:flex;justify-content:space-between;font-size:.87rem;
        font-weight:500;margin-bottom:3px}
.bar-bg{background:#e2e8f0;border-radius:5px;height:10px;overflow:hidden}
.bar-fill{height:100%;border-radius:5px;transition:width 1s ease}
.fill-ham     {background:linear-gradient(90deg,#16a34a,#4ade80)}
.fill-spam    {background:linear-gradient(90deg,#d97706,#fbbf24)}
.fill-phishing{background:linear-gradient(90deg,#dc2626,#f87171)}
/* Signals */
.sigs{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));
      gap:10px;margin-top:16px}
.sig{background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:10px 12px}
.sig-label{font-size:.72rem;color:#94a3b8;text-transform:uppercase;
           letter-spacing:.05em;margin-bottom:3px}
.sig-val{font-size:1.1rem;font-weight:700;color:#1e293b}
.sig-sub{font-size:.75rem;color:#94a3b8;margin-top:1px;word-break:break-word}
/* Warning */
.warn{border-radius:8px;padding:12px 14px;margin-top:14px;
      font-size:.9rem;font-weight:500;line-height:1.5}
.warn.ham     {background:#f0fdf4;color:#15803d;border:1px solid #bbf7d0}
.warn.spam    {background:#fffbeb;color:#b45309;border:1px solid #fde68a}
.warn.phishing{background:#fef2f2;color:#b91c1c;border:1px solid #fecaca}
/* Footer */
.foot{text-align:center;color:#94a3b8;font-size:.78rem;padding:20px 0 6px}
/* History */
.hist{margin-top:16px}
.hist h2{font-size:.8rem;font-weight:600;color:#94a3b8;text-transform:uppercase;
         letter-spacing:.07em;margin-bottom:8px}
.hi{background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:9px 12px;
    margin-bottom:6px;display:flex;align-items:center;gap:10px;cursor:pointer;
    transition:border-color .15s}
.hi:hover{border-color:#94a3b8}
.hi-txt{flex:1;font-size:.83rem;color:#64748b;
        white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.hi-lbl{font-size:.76rem;font-weight:600;padding:2px 7px;border-radius:4px}
.lbl-ham     {background:#f0fdf4;color:#15803d}
.lbl-spam    {background:#fffbeb;color:#b45309}
.lbl-phishing{background:#fef2f2;color:#b91c1c}
@media(max-width:560px){.verdict{font-size:1.2rem}.sigs{grid-template-columns:1fr 1fr}}
</style>
</head>
<body>
<div class="wrap">
  <div style="margin-bottom:20px">
    <h1>Email Threat Checker</h1>
    <div class="sub">Sathish Srinivasan &nbsp;|&nbsp; B01035250 &nbsp;|&nbsp; Dr. Roy Sterritt &nbsp;|&nbsp; Ulster University &nbsp;|&nbsp; COM748/COM766</div>
  </div>

  <div class="card">
    <h2>📧 Check Your Email</h2>

    <!-- CHECKBOX SELECTOR -->
    <div class="check-note">Select what you think this email is (optional — for comparison):</div>
    <div class="check-row">
      <label class="check-label" id="lbl-ham">
        <input type="checkbox" id="chk-ham" onchange="onCheck('ham')"> ✅ Legitimate (Ham)
      </label>
      <label class="check-label" id="lbl-spam">
        <input type="checkbox" id="chk-spam" onchange="onCheck('spam')"> ⚠️ Spam
      </label>
      <label class="check-label" id="lbl-phishing">
        <input type="checkbox" id="chk-phishing" onchange="onCheck('phishing')"> 🚨 Phishing
      </label>
    </div>

    <textarea id="emailInput"
      placeholder="Paste your full email text here...&#10;&#10;The model will classify it as:&#10;  ✅ Legitimate (Ham)&#10;  ⚠️ Spam&#10;  🚨 Phishing"></textarea>

    <div class="btn-row">
      <button class="btn-a" id="analyseBtn" onclick="analyse()">🔍 Analyse Email</button>
      <button class="btn-c" onclick="clearAll()">Clear</button>
    </div>
  </div>

  <div class="spinner" id="spinner"><span class="spin"></span>Analysing...</div>

  <div class="result" id="result">
    <div class="verdict" id="vLabel"></div>
    <div class="conf"   id="vConf"></div>
    <div id="matchLine" style="font-size:.9rem;font-weight:600;margin-bottom:14px"></div>

    <div class="bars">
      <h3>Class Probabilities</h3>
      <div class="bar-row">
        <div class="bar-hd"><span>✅ Legitimate (Ham)</span><span id="pHam">0%</span></div>
        <div class="bar-bg"><div class="bar-fill fill-ham" id="bHam" style="width:0%"></div></div>
      </div>
      <div class="bar-row">
        <div class="bar-hd"><span>⚠️ Spam</span><span id="pSpam">0%</span></div>
        <div class="bar-bg"><div class="bar-fill fill-spam" id="bSpam" style="width:0%"></div></div>
      </div>
      <div class="bar-row">
        <div class="bar-hd"><span>🚨 Phishing</span><span id="pPhish">0%</span></div>
        <div class="bar-bg"><div class="bar-fill fill-phishing" id="bPhish" style="width:0%"></div></div>
      </div>
    </div>

    <div class="sigs">
      <div class="sig">
        <div class="sig-label">URLs Found</div>
        <div class="sig-val" id="sUrl">—</div>
        <div class="sig-sub">Links in email</div>
      </div>
      <div class="sig">
        <div class="sig-label">Exclamation Marks</div>
        <div class="sig-val" id="sExcl">—</div>
        <div class="sig-sub">Urgency signal</div>
      </div>
      <div class="sig">
        <div class="sig-label">Caps Ratio</div>
        <div class="sig-val" id="sCaps">—</div>
        <div class="sig-sub">UPPERCASE usage</div>
      </div>
      <div class="sig">
        <div class="sig-label">Urgency Words</div>
        <div class="sig-val" id="sUrg">—</div>
        <div class="sig-sub" id="sUrgWords"></div>
      </div>
    </div>

    <div class="warn" id="warnBanner"></div>
  </div>

  <div class="hist" id="histSection" style="display:none">
    <div class="card" style="padding:16px">
      <h2>📋 Recent Checks</h2>
      <div id="histList"></div>
    </div>
  </div>

</div>

<script>
const ICONS  = {ham:"✅",spam:"⚠️",phishing:"🚨"};
const LABELS = {ham:"✅ LEGITIMATE (HAM)",spam:"⚠️ SPAM",phishing:"🚨 PHISHING"};
const WARNS  = {
  ham:      "✅ This email appears legitimate. No significant threat signals detected.",
  spam:     "⚠️ This email is likely unsolicited spam. Do NOT click any links or respond.",
  phishing: "🚨 WARNING — Strong phishing indicators detected. Do NOT click links, enter passwords, or share personal information. Report to your IT/security team immediately."
};
const EXAMPLES = {
  ham:      "Hi Sarah,\\n\\nJust confirming our meeting tomorrow at 10am in the boardroom. Please bring the Q3 reports and contract drafts for review.\\n\\nBest regards,\\nMark",
  spam:     "CONGRATULATIONS!!!\\n\\nYou have been SPECIALLY SELECTED to receive a FREE iPhone 15 Pro!!!\\n\\nCLICK HERE NOW to claim your prize before midnight: http://win-free-iphone.biz/claim\\n\\nLIMITED TIME OFFER — ACT NOW!!!",
  phishing: "Dear Customer,\\n\\nYour PayPal account has been limited due to unusual activity.\\n\\nPlease verify your information immediately at:\\nhttp://paypa1-secure-verify.com/login\\n\\nFailure to verify within 24 hours will result in permanent account suspension.\\n\\nPayPal Security Team"
};

let history=[], userGuess=null;

function onCheck(type){
  // Only one checkbox active at a time
  ["ham","spam","phishing"].forEach(t=>{
    document.getElementById("chk-"+t).checked = (t===type && document.getElementById("chk-"+t).checked);
    document.getElementById("lbl-"+t).className = "check-label" +
      (document.getElementById("chk-"+t).checked ? " active-"+t : "");
  });
  userGuess = document.getElementById("chk-"+type).checked ? type : null;
}

function loadEx(type){
  document.getElementById("emailInput").value = EXAMPLES[type];
  document.getElementById("emailInput").focus();
}

function clearAll(){
  document.getElementById("emailInput").value="";
  document.getElementById("result").style.display="none";
  ["ham","spam","phishing"].forEach(t=>{
    document.getElementById("chk-"+t).checked=false;
    document.getElementById("lbl-"+t).className="check-label";
  });
  userGuess=null;
}

async function analyse(){
  const txt = document.getElementById("emailInput").value.trim();
  if(!txt){
    document.getElementById("emailInput").style.borderColor="#dc2626";
    setTimeout(()=>document.getElementById("emailInput").style.borderColor="#e2e8f0",1500);
    return;
  }
  const btn=document.getElementById("analyseBtn");
  btn.disabled=true; btn.textContent="Analysing...";
  document.getElementById("spinner").style.display="block";
  document.getElementById("result").style.display="none";

  try{
    const resp=await fetch("/predict",{
      method:"POST",
      headers:{"Content-Type":"application/json"},
      body:JSON.stringify({email:txt})
    });
    const data=await resp.json();
    if(data.error){alert("Error: "+data.error);return;}
    showResult(data,txt);
    addHistory(data,txt);
  }catch(e){
    alert("Connection error: "+e.message+"\\nKeep the Colab cell running.");
  }finally{
    btn.disabled=false; btn.textContent="🔍 Analyse Email";
    document.getElementById("spinner").style.display="none";
  }
}

function showResult(data,txt){
  const lbl=data.label;
  const res=document.getElementById("result");
  res.className="result "+lbl;

  document.getElementById("vLabel").textContent=LABELS[lbl];
  document.getElementById("vLabel").className="verdict "+lbl;
  document.getElementById("vConf").textContent="Confidence: "+data.confidence.toFixed(1)+"%";

  // Checkbox comparison line
  const ml=document.getElementById("matchLine");
  if(userGuess){
    const correct=userGuess===lbl;
    ml.textContent = correct
      ? "✅ Your guess was correct! You identified it as "+userGuess.toUpperCase()+"."
      : "❌ Your guess was "+userGuess.toUpperCase()+" — the model says "+lbl.toUpperCase()+".";
    ml.style.color = correct ? "#15803d" : "#b91c1c";
  } else {
    ml.textContent="";
  }

  setTimeout(()=>{
    setBar("pHam","bHam",data.ham_pct);
    setBar("pSpam","bSpam",data.spam_pct);
    setBar("pPhish","bPhish",data.phishing_pct);
  },60);

  document.getElementById("sUrl").textContent=data.url_count;
  document.getElementById("sExcl").textContent=data.exclamations;
  document.getElementById("sCaps").textContent=data.caps_ratio+"%";
  document.getElementById("sUrg").textContent=data.urgency_words.length;
  document.getElementById("sUrgWords").textContent=
    data.urgency_words.length>0 ? data.urgency_words.slice(0,5).join(", ") : "none detected";

  const wb=document.getElementById("warnBanner");
  wb.textContent=WARNS[lbl]; wb.className="warn "+lbl;
  res.style.display="block";
  res.scrollIntoView({behavior:"smooth",block:"nearest"});
}

function setBar(pid,bid,val){
  document.getElementById(pid).textContent=val.toFixed(1)+"%";
  document.getElementById(bid).style.width=Math.min(val,100)+"%";
}

function addHistory(data,txt){
  history.unshift({label:data.label,text:txt,conf:data.confidence.toFixed(1)});
  if(history.length>6)history.pop();
  const sec=document.getElementById("histSection");
  sec.style.display="block";
  document.getElementById("histList").innerHTML=history.map((h,i)=>`
    <div class="hi" onclick="loadHist(${i})">
      <span>${ICONS[h.label]}</span>
      <span class="hi-txt">${h.text.replace(/\\n/g," ").substring(0,80)}...</span>
      <span class="hi-lbl lbl-${h.label}">${h.label.toUpperCase()} ${h.conf}%</span>
    </div>`).join("");
}

function loadHist(i){
  document.getElementById("emailInput").value=history[i].text;
  window.scrollTo({top:0,behavior:"smooth"});
}

document.addEventListener("keydown",e=>{
  if((e.ctrlKey||e.metaKey)&&e.key==="Enter")analyse();
});
</script>
</body>
</html>"""

@website_app.route("/")
def _home():
    return WEBSITE_HTML

@website_app.route("/predict", methods=["POST","OPTIONS"])
def _predict():
    if request.method == "OPTIONS":
        resp = jsonify({})
        resp.headers["Access-Control-Allow-Origin"] = "*"
        resp.headers["Access-Control-Allow-Headers"] = "Content-Type"
        return resp, 200
    try:
        data       = request.get_json(force=True)
        email_text = data.get("email","").strip()
        if not email_text:
            resp = jsonify({"error":"No email text provided"})
            resp.headers["Access-Control-Allow-Origin"] = "*"
            return resp, 400
        result = predict_email(email_text)
        resp = jsonify(result)
        resp.headers["Access-Control-Allow-Origin"] = "*"
        return resp
    except Exception as e:
        resp = jsonify({"error":str(e)})
        resp.headers["Access-Control-Allow-Origin"] = "*"
        return resp, 500

def _run_site():
    website_app.run(host="0.0.0.0", port=5000, debug=False,
                    use_reloader=False, threaded=True)

_t = threading.Thread(target=_run_site, daemon=True)
_t.start()
time.sleep(3)

from google.colab.output import eval_js
print("\n  Website is live!")
try:
    # Get the public Colab proxy URL for port 5000 — works instantly, no token
    public_url = eval_js("google.colab.kernel.proxyPort(5000)")
    print(f"\n  🔗  Click to open your website:")
    print(f"\n      {public_url}\n")
    from IPython.display import display, HTML
    display(HTML(
        f'<div style="margin:12px 0;padding:14px 20px;background:#f0fdf4;'
        f'border:2px solid #16a34a;border-radius:10px;font-family:sans-serif">'
        f'<div style="font-size:1.05rem;font-weight:700;color:#15803d;margin-bottom:6px">'
        f'Website is Live!</div>'
        f'<a href="{public_url}" target="_blank" '
        f'style="font-size:1rem;color:#2563eb;font-weight:600">'
        f'👉 Click here to open the website in a new tab</a>'
        f'<div style="margin-top:8px;font-size:.85rem;color:#64748b">'
        f'No token or signup required. Keep this cell running while using the website.</div>'
        f'</div>'
    ))
except Exception:
    # Fallback — show the localhost URL with Colab port instructions
    print("\n  ✅  Website is running on port 5000.")
    print("\n  To open it, click the link below:")
    try:
        from IPython.display import display, HTML
        display(HTML(
            '<div style="margin:12px 0;padding:14px 20px;background:#eff6ff;'
            'border:2px solid #2563eb;border-radius:10px;font-family:sans-serif">'
            '<b style="color:#1d4ed8">To open the website:</b><br><br>'
            '1. Look at the <b>bottom-right corner</b> of this Colab page<br>'
            '2. Click the <b>🔌 port icon</b> (or "Ports" tab)<br>'
            '3. Click <b>port 5000</b> — the website opens in a new tab<br>'
            '<br><span style="color:#64748b;font-size:.85rem">'
            'Keep this cell running while using the website.</span>'
            '</div>'
        ))
    except Exception:
        pass

# SECTION 13 — ⬇️  AUTO DOWNLOAD ALL OUTPUT FILES
# All 9 output files download automatically — no copy-paste needed.
print("SECTION 13 — ⬇️  AUTO DOWNLOADING OUTPUT FILES")

OUTPUT_FILES = [
    ("eda_visualisations.png",     "EDA 9-panel charts"),
    ("baseline_results.csv",       "Baseline model metrics"),
    ("roberta_best.pt",            "Saved RoBERTa weights"),
    ("roberta_training_curve.png", "RoBERTa training curves"),
    ("shap_phishing.png",          "SHAP phishing class plot"),
    ("shap_all_classes.png",       "SHAP all classes bar chart"),
    ("final_all_results.csv",      "All model results table"),
    ("final_model_comparison.png", "Final bar chart comparison"),
    ("confusion_matrices.png",     "Confusion matrices"),
]

print("\n  Files ready:")
for fname, desc in OUTPUT_FILES:
    status = "✅" if os.path.exists(fname) else "❌"
    print(f"  {status}  {fname:<42} {desc}")

print("\n  Downloading all files to your computer now...\n")
downloaded = 0
for fname, desc in OUTPUT_FILES:
    if os.path.exists(fname):
        try:
            files.download(fname)
            print(f"  ⬇️   {fname}")
            downloaded += 1
            time.sleep(0.8)
        except Exception as e:
            print(f"  ⚠️   Could not download {fname}: {e}")
    else:
        print(f"  ❌  {fname} — not found (may not have been generated)")

print(f"\n  ✅  {downloaded}/{len(OUTPUT_FILES)} files downloaded automatically")

print("\n  💾  Saving all output files to Google Drive...")
try:
    from google.colab import drive
    import shutil
    drive.mount("/content/drive")
    folder = "/content/drive/MyDrive/EmailChecker_Project"
    os.makedirs(folder, exist_ok=True)
    saved_drive = 0
    for f in OUTPUT_FILES:
        fname = f[0]
        if os.path.exists(fname):
            shutil.copy(fname, folder)
            print(f"  ✅  Saved to Drive: {fname}")
            saved_drive += 1
        else:
            print(f"  ❌  Not found: {fname}")
    print(f"\n  {saved_drive}/{len(OUTPUT_FILES)} files saved to Google Drive")
    print(f"  📁  Location: My Drive > EmailChecker_Project")
except Exception as e:
    print(f"  ⚠️  Google Drive save skipped: {e}")
print("\n  All done.")